// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/anillos" | "/humo" | "/jugar" | "/lab" | "/lab/anillos" | "/lab/radio" | "/loop" | "/qr" | "/radio" | "/reel"
type AppRouteHandlerRoutes = "/api/anillos/leaderboard" | "/api/anillos/run/finish" | "/api/anillos/run/start" | "/api/arcade/playtest" | "/api/humo/capture" | "/api/humo/leaderboard" | "/api/humo/run/finish" | "/api/humo/run/start" | "/api/pulso/interest" | "/api/pulso/leaderboard" | "/api/pulso/run/finish" | "/api/pulso/run/start" | "/api/radio/leaderboard" | "/api/radio/run/finish" | "/api/radio/run/start"
type PageRoutes = never
type LayoutRoutes = "/" | "/lab"
type RedirectRoutes = "/anillos" | "/humo" | "/lab/muro" | "/lab/salida" | "/muro" | "/radio" | "/salida"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/anillos": {}
  "/api/anillos/leaderboard": {}
  "/api/anillos/run/finish": {}
  "/api/anillos/run/start": {}
  "/api/arcade/playtest": {}
  "/api/humo/capture": {}
  "/api/humo/leaderboard": {}
  "/api/humo/run/finish": {}
  "/api/humo/run/start": {}
  "/api/pulso/interest": {}
  "/api/pulso/leaderboard": {}
  "/api/pulso/run/finish": {}
  "/api/pulso/run/start": {}
  "/api/radio/leaderboard": {}
  "/api/radio/run/finish": {}
  "/api/radio/run/start": {}
  "/humo": {}
  "/jugar": {}
  "/lab": {}
  "/lab/anillos": {}
  "/lab/muro": {}
  "/lab/radio": {}
  "/lab/salida": {}
  "/loop": {}
  "/muro": {}
  "/qr": {}
  "/radio": {}
  "/reel": {}
  "/salida": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/lab": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
