// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/anillos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/anillos">> = Specific
  const handler = {} as typeof import("../../app/anillos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/humo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/humo">> = Specific
  const handler = {} as typeof import("../../app/humo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/jugar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jugar">> = Specific
  const handler = {} as typeof import("../../app/jugar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/anillos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/anillos">> = Specific
  const handler = {} as typeof import("../../app/lab/anillos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab">> = Specific
  const handler = {} as typeof import("../../app/lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/radio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/radio">> = Specific
  const handler = {} as typeof import("../../app/lab/radio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/ranking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/ranking">> = Specific
  const handler = {} as typeof import("../../app/lab/ranking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/loop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/loop">> = Specific
  const handler = {} as typeof import("../../app/loop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/qr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/qr">> = Specific
  const handler = {} as typeof import("../../app/qr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/radio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/radio">> = Specific
  const handler = {} as typeof import("../../app/radio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reel">> = Specific
  const handler = {} as typeof import("../../app/reel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/anillos/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/anillos/leaderboard">> = Specific
  const handler = {} as typeof import("../../app/api/anillos/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/anillos/run/finish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/anillos/run/finish">> = Specific
  const handler = {} as typeof import("../../app/api/anillos/run/finish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/anillos/run/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/anillos/run/start">> = Specific
  const handler = {} as typeof import("../../app/api/anillos/run/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/arcade/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/leaderboard">> = Specific
  const handler = {} as typeof import("../../app/api/arcade/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/arcade/playtest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade/playtest">> = Specific
  const handler = {} as typeof import("../../app/api/arcade/playtest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/humo/capture/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/humo/capture">> = Specific
  const handler = {} as typeof import("../../app/api/humo/capture/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/humo/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/humo/leaderboard">> = Specific
  const handler = {} as typeof import("../../app/api/humo/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/humo/run/finish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/humo/run/finish">> = Specific
  const handler = {} as typeof import("../../app/api/humo/run/finish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/humo/run/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/humo/run/start">> = Specific
  const handler = {} as typeof import("../../app/api/humo/run/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pulso/interest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pulso/interest">> = Specific
  const handler = {} as typeof import("../../app/api/pulso/interest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pulso/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pulso/leaderboard">> = Specific
  const handler = {} as typeof import("../../app/api/pulso/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pulso/run/finish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pulso/run/finish">> = Specific
  const handler = {} as typeof import("../../app/api/pulso/run/finish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pulso/run/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pulso/run/start">> = Specific
  const handler = {} as typeof import("../../app/api/pulso/run/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/radio/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/radio/leaderboard">> = Specific
  const handler = {} as typeof import("../../app/api/radio/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/radio/run/finish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/radio/run/finish">> = Specific
  const handler = {} as typeof import("../../app/api/radio/run/finish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/radio/run/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/radio/run/start">> = Specific
  const handler = {} as typeof import("../../app/api/radio/run/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/lab/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/lab">> = Specific
  const handler = {} as typeof import("../../app/lab/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
