/** Copy de ANTES DEL HUMO. Máximo dos líneas de instrucción. */

export const humoCopy = {
  title: 'AURA: ANTES DEL HUMO',
  kicker: 'Ruta de escape',
  landingAsk: '¿Llegás antes del humo?',
  cta: 'JUGÁ 40 S',
  hint: 'Del verde al naranja.',
  draw: 'Arrastrá al fuego',
  coach: 'Base → fuego',
  coachWait: 'Ahí viene',
  send: 'Soltá',
  mute: 'Sonido off',
  sound: 'Sonido',
  ha: 'ha protegidas',
  rematch: 'Otra ruta',
  share: 'WhatsApp',
  copied: 'Copiado',
  rankToday: 'Hoy',
  gapLead: 'Vas 1°',
  newRecord: 'Récord',
  skipAlias: 'Seguir',
  aliasLabel: 'Apodo (opcional)',
  saveAlias: 'Poner en el ranking',
  offline: 'Sin red · misma ronda',
  standQr: 'Escaneá y jugá',
  standUrl: 'aura.ia.bo/jugar',
  standBoard: 'Hoy',
  standKeys: 'Q código · L ranking',
  standInterest: 'Ping',
  standFair: (alias: string, score: number) => `${alias} ${score} ha`,
  medalAlerta: 'ALERTA',
  medalRuta: 'RUTA CLARA',
  medalOjo: 'OJO DE FUEGO',
  etaGreen: 'Llega',
  etaAmber: 'Justo',
  etaRed: 'Tarde',
  plusHa: (n: number) => `+${n} ha`,
  gap: (n: number) => `−${n} ha`,
  yourBest: (n: number) => `Mejor ${n} ha`,
  shareText: (ha: number, title: string, url: string, rank?: number | null) => {
    const rankBit = rank === 1 ? '1° hoy. ' : rank && rank > 1 ? `${rank}° hoy. ` : ''
    return `Salvé ${ha} ha — ${title}. ${rankBit}¿Mejorás la ruta? ${url}`
  },
  juice: {
    SAVE: '¡SÍ!',
    SAVE_BIG: 'PREDIO',
    ARRIVE: 'TARDE',
    MISS: 'SE QUEMÓ',
    CLUTCH: 'YA',
    GUIDE: 'Este camino',
  },
} as const
