/** Copy de ANTES DEL HUMO: siempre español. Corto. */

export const humoCopy = {
  title: 'AURA: ANTES DEL HUMO',
  hint: 'DEL VERDE AL NARANJA',
  ghost: '',
  draw: 'Arrastrá',
  coach: 'Al fuego',
  coachWait: 'Ahí viene',
  coachDrag: 'Camino = más ha',
  send: 'Mandar',
  clickFire: 'FUEGO',
  cancelHint: 'Al fuego',
  combo: 'Ruta',
  focos: 'Focos',
  ha: 'ha',
  predio: 'Fexpocruz',
  mute: 'Silencio',
  sound: 'Sonido',
  endTitle: '',
  rankToday: 'Hoy',
  ofToday: (total: number) => `/${total}`,
  gap: (n: number) => `−${n} ha`,
  gapLead: 'Vas 1°',
  newRecord: 'Récord',
  yourBest: (n: number) => `Mejor ${n} ha`,
  won: 'Título',
  wonBody: '',
  rematch: 'Otra',
  share: 'WhatsApp',
  copied: 'Copiado',
  follow: '',
  brand: '',
  icp: '¿Campo o brigada?',
  icpCta: 'WhatsApp Aura',
  aliasLabel: 'Apodo',
  saveAlias: 'Guardar',
  skipAlias: 'Dejar',
  otherAlias: 'Otro',
  fb: 'Facebook',
  li: 'LinkedIn',
  ig: 'Instagram',
  standQr: 'Escaneá y jugá',
  standUrl: 'aura.ia.bo/pulso',
  standBoard: 'Hoy',
  standKeys: 'Q código · L ranking',
  standInterest: 'Ping',
  standFair: (alias: string, score: number) => `${alias} ${score} ha`,
  offline: 'Sin red',
  mission: 'Hoy',
  missionDone: 'Listo',
  missionLeft: (n: number) => `faltan ${n}`,
  toBeat: (n: number) => `1°: ${n}`,
  beatLead: 'Le ganaste al 1°',
  plays: (n: number) => `#${n}`,
  challenge: '¿Me ganás?',
  sameSeed: 'Mismo predio',
  plusHa: (n: number) => `+${n}`,
  ghostHa: (n: number) => (n > 0 ? `+${n}` : 'Al fuego'),
  window: '',
  racha: 'x',
  shareText: (ha: number, title: string, url: string, rank?: number | null) => {
    const rankBit = rank === 1 ? '1° hoy. ' : rank && rank > 1 ? `${rank}° hoy. ` : ''
    return `Salvé ${ha} ha — ${title}. ${rankBit}¿Me ganás? ${url}`
  },
  juice: {
    SAVE: '¡SÍ!',
    SAVE_BIG: '¡PREDIO!',
    ARRIVE: 'TARDE',
    MISS: 'FALLÓ',
    NODE: 'NODO',
    FIRE: 'FUEGO',
    CUT: 'CORTÓ',
    ROAD: 'CAMINO',
    STREAK2: 'x2',
    STREAK3: 'x3',
    CLUTCH: 'YA',
    FOCO: (n: number) => `${n}/3`,
  },
} as const
