/** Copy de ANTES DEL HUMO. Máximo dos líneas de instrucción. */

export const humoCopy = {
  title: 'AURA: ANTES DEL HUMO',
  kicker: 'Ruta de escape',
  landingAsk: '¿Llegás antes del humo?',
  cta: 'JUGÁ 40 S',
  hint: 'Del verde al naranja.',
  draw: 'Arrastrá al fuego',
  coach: 'Base → fuego',
  coachWait: 'Ahí viene',
  send: 'Soltá',
  mute: 'Sonido apagado',
  sound: 'Sonido',
  ha: 'ha protegidas',
  rematch: 'OTRA RUTA',
  share: 'Desafiar a alguien',
  copied: 'Copiado',
  rankToday: 'Ranking de hoy',
  gapLead: 'Vas 1°',
  newRecord: 'Tu mejor',
  leftover: 'Te quedó una ruta.',
  skipAlias: 'Seguir',
  aliasLabel: 'Apodo (opcional)',
  saveAlias: 'Firmar esta ronda',
  offline: 'Sin conexión',
  offlineBoard: 'Sin conexión; tu mejor ronda sigue acá',
  standQr: 'ESCANEÁ Y JUGÁ',
  standUrl: 'aura.ia.bo/jugar',
  standBoard: 'Hoy',
  standKeys: 'Q código · L ranking',
  standInterest: 'Ping',
  standFair: (alias: string, score: number) => `${alias} ${score} ha`,
  medalAlerta: 'ALERTA',
  medalRuta: 'RUTA CLARA',
  medalOjo: 'OJO DE FUEGO',
  etaGreen: 'LLEGA',
  etaAmber: 'JUSTO',
  etaRed: 'TARDE',
  plusHa: (n: number) => `+${n} ha`,
  gap: (n: number) => `−${n} ha`,
  yourBest: (n: number) => `Mejor ${n} ha`,
  dayBest: (n: number) => `Hoy ${n} ha`,
  shareText: (ha: number, title: string, url: string, rank?: number | null) => {
    const rankBit = rank === 1 ? '1° hoy. ' : rank && rank > 1 ? `${rank}° hoy. ` : ''
    return `Jugué ANTES DEL HUMO: ${ha} ha, ${title}. ${rankBit}¿Mejorás la ruta? ${url}`
  },
  juice: {
    SAVE: 'LLEGÓ',
    SAVE_BIG: 'PREDIO',
    ARRIVE: 'JUSTO',
    MISS: 'TARDE',
    CLUTCH: 'YA',
    GUIDE: 'Este camino',
  },
} as const
