/** Copy del juego: siempre español. No pasar por next-intl (el browser en EN lo rompe). */

export const pulsoCopy = {
  title: 'AURA PULSO',
  hint: 'TOCÁ EN EL MOMENTO JUSTO',
  ghost: 'Tu predio en el mapa. Los focos vienen del monte. Tocá cuando el pulso los cubra.',
  tap: 'Tocá pues',
  combo: 'Racha',
  rush: '¡SE PRENDIÓ TODO!',
  focos: 'Focos',
  predio: 'Predio Fexpocruz',
  mute: 'Silencio',
  sound: 'Sonido',
  endTitle: 'Se acabó el pulso',
  rankToday: 'Puesto de hoy',
  ofToday: (total: number) => `de ${total}`,
  gap: (n: number) => `Te faltaron ${n} para cazar al de adelante`,
  gapLead: 'Vas primero hoy, camba',
  newRecord: '¡Récord tuyo!',
  yourBest: (n: number) => `Tu mejor: ${n}`,
  won: 'Lo que te llevás',
  wonBody:
    'Título en el pizarrón del stand, puesto de hoy y un recorte para el grupo. No hay plata: hay fama. Mañana cambia la misión.',
  rematch: 'Otra, pues',
  share: 'Mandar recorte',
  copied: 'Copiado. Pegalo en el grupo.',
  follow: 'Seguinos',
  brand: 'Aura baja el fuego a territorio. 20 min. Santa Cruz.',
  icp: '¿Andás en campo, brigada o municipio?',
  icpCta: 'Escribile a Aura por WhatsApp',
  aliasLabel: 'Tu nombre en el ranking',
  saveAlias: 'Dejar este nombre',
  skipAlias: 'Dejar el apodo que ya tienes',
  otherAlias: 'Otro apodo',
  fb: 'Facebook',
  li: 'LinkedIn',
  ig: 'Instagram',
  standQr: 'Escaneá y jugá',
  standUrl: 'aura.ia.bo/pulso',
  standBoard: 'Ranking de hoy',
  standKeys: 'Q código · L ranking · V video',
  standInterest: 'Último ping de campo',
  standFair: (alias: string, score: number) => `Récord feria: ${alias} ${score}`,
  offline: 'Sin red: el puntaje queda en el celu.',
  mission: 'Misión de hoy',
  missionDone: 'Misión cumplida, camba',
  missionLeft: (n: number) => `Te faltan ${n}`,
  toBeat: (n: number) => `Para ser 1°: ${n}`,
  beatLead: 'Le ganaste al 1° del día',
  plays: (n: number) => (n <= 1 ? 'Primera partida' : `Partida ${n}`),
  stars: 'Estrellas',
  shareText: (score: number, title: string) =>
    `Soy ${title} en AURA PULSO (${score} pts) en Fexpocruz. ¿Me ganás? aura.ia.bo/pulso`,
  juice: {
    PERFECT: '¡CLAVADO!',
    DOBLE: '¡DOBLE!',
    CASI: '¡CASI PUES!',
    BRECHA: '¡SE METIÓ!',
    MISS: '¡AIRE!',
  } as Record<string, string>,
} as const
